# coding: utf-8

"""
    API Subscriptions Sandbox

    This API lets you manage the subscriptions to API Hub asynchronous events. It enables you to receive notifications (asynchronous events) from Círculo de Crédito next-generation products (Open Banking & Data Aggregation).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: api@circulodecredito.com.mx
"""


import pprint
import re  # noqa: F401

import six


class Links(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_self': 'str',
        'first': 'str',
        'previous': 'str',
        'next': 'str',
        'last': 'str'
    }

    attribute_map = {
        '_self': 'self',
        'first': 'first',
        'previous': 'previous',
        'next': 'next',
        'last': 'last'
    }

    def __init__(self, _self=None, first=None, previous=None, next=None, last=None):  # noqa: E501
        """Links - a model defined in Swagger"""  # noqa: E501

        self.__self = None
        self._first = None
        self._previous = None
        self._next = None
        self._last = None
        self.discriminator = None

        if _self is not None:
            self._self = _self
        if first is not None:
            self.first = first
        if previous is not None:
            self.previous = previous
        if next is not None:
            self.next = next
        if last is not None:
            self.last = last

    @property
    def _self(self):
        """Gets the _self of this Links.  # noqa: E501

        URL of this page.  # noqa: E501

        :return: The _self of this Links.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this Links.

        URL of this page.  # noqa: E501

        :param _self: The _self of this Links.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def first(self):
        """Gets the first of this Links.  # noqa: E501

        URL of the first page.  # noqa: E501

        :return: The first of this Links.  # noqa: E501
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this Links.

        URL of the first page.  # noqa: E501

        :param first: The first of this Links.  # noqa: E501
        :type: str
        """

        self._first = first

    @property
    def previous(self):
        """Gets the previous of this Links.  # noqa: E501

        URL of the previous page.  # noqa: E501

        :return: The previous of this Links.  # noqa: E501
        :rtype: str
        """
        return self._previous

    @previous.setter
    def previous(self, previous):
        """Sets the previous of this Links.

        URL of the previous page.  # noqa: E501

        :param previous: The previous of this Links.  # noqa: E501
        :type: str
        """

        self._previous = previous

    @property
    def next(self):
        """Gets the next of this Links.  # noqa: E501

        URL of the next page.  # noqa: E501

        :return: The next of this Links.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this Links.

        URL of the next page.  # noqa: E501

        :param next: The next of this Links.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def last(self):
        """Gets the last of this Links.  # noqa: E501

        URL of the last page.  # noqa: E501

        :return: The last of this Links.  # noqa: E501
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this Links.

        URL of the last page.  # noqa: E501

        :param last: The last of this Links.  # noqa: E501
        :type: str
        """

        self._last = last

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Links, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
